batch_size: 2
body_weight: 0.5
bundle_dirs:
- '0'
- '1'
- '2'
- '3'
cache_dir: ./cache/identity_preserving
content_weight: 0.5
data_dir: dataset_creation/data/dataset
device: cuda
face_weight: 1.0
log_interval: 10
lr: 0.0001
max_chars_per_bundle: 50
min_images_per_char: 3
num_body_latents: 16
num_epochs: 2
num_face_latents: 16
num_fused_latents: 32
num_workers: 4
output_dir: ./checkpoints/identity_preserving
run_name: identity_preserving_v1
seed: 42
test_split: 0.1
use_amp: true
use_cache: true
use_identity_fusion: true
use_wandb: false
val_split: 0.1
wandb_project: identity-preserving-flux
weight_decay: 1.0e-05
