# Identity Preservation Model Training Configuration

# Dataset parameters
data_dir: "dataset_creation/data/dataset"
bundle_dirs: ["0", "1", "2", "3"]  # Use first 4 bundles
max_chars_per_bundle: 50  # Limit characters per bundle to prevent memory issues
min_images_per_char: 3  # Minimum number of images per character
cache_dir: "./cache/identity_preserving"
use_cache: true  # Enable caching of extracted features

# Model parameters
num_face_latents: 16
num_body_latents: 16
num_fused_latents: 32
use_identity_fusion: true

# Training parameters
batch_size: 4
num_epochs: 50
lr: 0.0001
weight_decay: 0.00001
face_weight: 1.0
body_weight: 0.5
content_weight: 0.5
val_split: 0.1
test_split: 0.1
use_amp: true  # Enable automatic mixed precision
num_workers: 4
log_interval: 10
device: "cuda"
seed: 42

# Output parameters
output_dir: "./checkpoints/identity_preserving"
run_name: "identity_preserving_v1"

# Wandb parameters
use_wandb: true
wandb_project: "identity-preserving-flux" 