data_dir: "dataset"
max_chars_per_bundle: 20
min_images_per_char: 3
reference_image_idx: 0
cache_dir: "cache/identity_preserving"
use_cache: true

input_size: 512
num_face_latents: 16
num_body_latents: 16
face_injection_index: 17
body_injection_index: 9

batch_size: 2
num_epochs: 30
learning_rate: 0.0001
weight_decay: 0.00001
face_weight: 1.0
body_weight: 0.5
content_weight: 0.5
val_split: 0.1
test_split: 0.1
use_amp: false
num_workers: 2
log_interval: 5
save_interval: 1
device: "cuda"
seed: 42

guidance_scale: 7.0
num_inference_steps: 10

output_dir: "checkpoints/identity_preserving"
run_name: "identity_preserving_flux"

use_wandb: false
wandb_project: "identity-preserving-flux" 